### ISSUE TITLE
Feedback M2

### ISSUE THREAD

**Issue by Danthar** [FAForever/NomadMissions#24]
on hard this map is impossible even with resource rich.

== on medium difficulty ==

Played with resource rich, otherwise you simply cannot ramp up quickly enough. and you wont be able to produce enough units to defend yourself in my experience. 
After clearing your landing zone. And destroying the upper naval base. I started targetting the cybran with air. This went well. 
Triggered the first expansion event. Que lots of naval.
With resource rich i have build up a sizable t1 naval group. consisting of 20 frigates and 30+ subs. 

It was not enough to destroy the top left base. The fleet was massacred by T2 naval before it even got close.
After that rebuilding your naval is pointless. Since you are never able to build up enough forces quickly enough to counter the t2 naval. And groups of amphibious t2 roaming the sea.

So i tried with the t1 air i had left. This helped for a while. But eventually the former cybran naval base was colonized by Blue. Which started producing air and more naval. 
At this point, the game is lost.

Once T2 naval has grouped up. The amount AA and TML it outputs is impossible to counter with the low amounts of air you manage to group up. Anything you group is, is intercepted by t2 air. So your resources are going into t2 fighter bombers, which are not very effective against T2 naval. At this point any t1 static defense is almost pointless.

Meanwhile amphibious groups are pushing from the left. A total lack of shields and t2 static defences, means you have to put units there. Which means a constant churn of units being destroyed and reclaimed. 
Eventually T2 naval destroyers&cruisers group up, and wipe the left side of the base, since you dont have TML defense.

But amphibious tanks are also coming from the top right.. Again. No static t2 defense. Means you have to put your own amphibious tanks in front. Which is owned by naval & air.

Not having T2 naval. or even just T2 static AA. really hurts, because you are constantly spending mass to defend yourself. while unable to mount an offense because any unit you make immediatly has to go into defense, and/or is shot down shortly. 
Any left over capacity is spend sending units to the cybran base to defend the civilians.

Not to mention the 2 bases from blue over there. The T3 arty is not directly accesable. So you have to either airlift units nearby. or drive around.

Im at attempt 5 now. And ill probably try a few more times. But you have to be super aggressive to win this map. However you have really limited resources. You wont even have t2 extractors untill later on. And even then most of your extractors are near the shore. Which means they are constantly destroyed by air and naval. 

This pushes you into massfabs. Which means it takes even longer to ramp up. And more resources which are not going into producing units. 
By the time i have a stable mass and power income, and can expand production. Your to late. Since the T3 arty is already destroying all the things.

What might help is:

when you get T2 access (in order of preference)
- Allow T2 AA OR shields
- Allow T2 naval
- Allow TML defense 

Overall i like the concept of the campaign so far. But it does forces you to have a really aggressive playstyle. And once you lose your mean battlegroup of t1 units (naval/air) there is no way to come back from that since you simply lack the resources to build up quickly enough to group a sizable force to punch through their defenses.
Grouping up t2 units costs even more resources. I thing that if you have better fortification options to defend what you have, without spending so much mass. It would allow for more playstyles. And make it easier to actually go after the objectives with t2 units. :)

**Comment by Danthar** [comment]
If you feel like im missing something obvious. Feel free to point it out :P

**Comment by Danthar** [comment]
And now i feel stupid because i just won the map with a gazillion t2 gunships :P

I still feel that my original remarks about not being able to ramp up quickly enough still stand.

**Comment by Shadowlorda1** [comment]
Hey, I am the mission maker for this one. I don't understand your comments about this being impossible. So far all of the nomad mod leadership has completed this mission on hard with no mods or resource enhancements, including me. Everything the enemy sends at you is fuel to your own eco and forces. Once you survive enough attacks and have reclaimed then you should be able to ramp up your own eco and began chipping away at enemy forces.

**Comment by Danthar** [comment]
Then i must be doing something wrong. I turned off timed expansions, to give myself more time. But even then i feel like im being overwhelmed. When was the last time you finished the map ? There have been quite a few balance patches for FaF which impact the mission balance. 

But if you say its possible :P then ill keep at it.

I just beat it at medium with resource rich. Ill try and build up from here.

Btw: satisfying death scream from that UEF commander in the end :D

**Comment by Exotic-Retard** [comment]
it seems you are pretty active with the missions, why dont you pop over on the nomads discord to discuss these things in a more convenient manner :>

https://discord.gg/Tqar3cu

Otherwise, the key to winning campaign missions in general is to reclaim everything, since that is 80-90% of your mass income quite often. Its hard to comment on what you are doing since the replay i checked out in the other mission desynced for me so i wasnt able to check how you were playing the game too accurately. But yeah the missions are fairly straightforward, though hard difficulty is indeed intended to be hard! You will need to use every trick in the book to beat them. (and in my view that difficulty isnt hard enough because i can still win! )

Anyway, since this is a discussion as opposed to a bug/feature, im closing this issue. However absolutely do feel free to continue chatting here if the discord doesnt work out for some reason :>
